### ISSUE TITLE
[BUG] ConfigurationException: The value of field 'permission' is null.

### ISSUE THREAD

**Issue by DntDmme** [Silthus/sLimits#23]
**I am getting an error = 
>.... [10:42:36 ERROR]: Could not pass event BlockPlaceEvent to slimits v1.8.0
net.silthus.slimits.slib.configlib.ConfigurationException: The value of field 'permission' is null.
Please assign a non-null default value or remove this field.**

**Screenshots**

**Server Information (please complete the following information):**
- Server version (`/bukkit:version`): Paper 1.16.5
- Installed plugins (`/bukkit:plugins`): 
- WorldGuard Report Pastebin Link (`/wg report -p`): Instakked

**Additional context**
I am getting error on the permission , i tried it reinstalling plugin but its same . 
![image](https://user-images.githubusercontent.com/73005308/119322065-b738c780-bc96-11eb-8d38-a9ebc566191f.png)
![image](https://user-images.githubusercontent.com/73005308/119322210-de8f9480-bc96-11eb-8c7b-907a981c8731.png)
![image](https://user-images.githubusercontent.com/73005308/119322259-e818fc80-bc96-11eb-9c27-661dc5d14064.png)

**Comment by Silthus** [comment]
Thank you for the detailed bug report, I will look into it shortly.

**Comment by Silthus** [comment]
Resolved with the 2.0.0 release.
