### ISSUE TITLE
Upgrade to Minecraft 1.17

### ISSUE THREAD

**Issue by Silthus** [Silthus/sLimits#27]
I will upgrade the plugin to be compatible with Minecraft 1.17 and also solve some other issues it has. A config change may be necessary. If so I will post it in the changelogs.

**Comment by REALMWTH** [comment]
Hi! Any progress?

**Comment by Silthus** [comment]
Yes, I will publish a pre-release in the next one to two weeks.
The update will also contain some new overall features.

**Comment by Silthus** [comment]
You can find a first working version here: https://github.com/Silthus/sLimits/releases/tag/v2.0.0-beta.4
Please note the different config and storage: https://github.com/Silthus/sLimits/blob/beta/Readme.md

**Comment by trevor1097** [comment]
Everything seem to be working great. the only issue that i am seeing is if a player has a hight limit permission it doesn't over ride the lower one and keep the player from placing bloc
<img width="570" alt="Screen Shot 2021-10-02 at 11 59 00 AM" src="https://user-images.githubusercontent.com/7597614/135727386-17431d24-648b-4eea-b794-19854f525596.png">
ks

**Comment by Silthus** [comment]
> Everything seem to be working great. the only issue that i am seeing is if a player has a hight limit permission it doesn't over ride the lower one and keep the player from placing blocks <img alt="Screen Shot 2021-10-02 at 11 59 00 AM" width="570" src="https://user-images.githubusercontent.com/7597614/135727386-17431d24-648b-4eea-b794-19854f525596.png">

Is it an option to only give the higher permission, or do you want limits for the same block type to overwrite each other and always count the highest limit?

**Comment by trevor1097** [comment]
I think for limits with the same block type they highest should overwrite each other

**Comment by Silthus** [comment]
Resolved with the [2.0.0 release](https://github.com/Silthus/sLimits/releases).
