### ISSUE TITLE
Permissions not working 

### ISSUE THREAD

**Issue by trevor1097** [Silthus/sLimits#5]
**Describe the bug**
Doesn't seem to register permissions.

If i am not oped it says that that i have no available placements (0/0) but when i op myself ALL of the limits take effect, even the ones above my group. So now it is showing (0/10) but i have to be oped for this to work.

**Comment by Silthus** [comment]
Can you please do a `wg report -p` and paste the pastebin link here?

Also what permissions are you giving yourself and how is your config structure?
Can you please attach an excerpt of the config that is not working?

**Comment by trevor1097** [comment]
Okay so i was using the permission `slimits.limits.merchant` based on the documentation. the permission is actually `slimits.limit.merchant`. when i changed them it works fine now.

**Comment by Silthus** [comment]
Oh you are right, thanks!

I will keep this open to track the docs bug.
