### ISSUE TITLE
Handling blocks destroyed by other players

### ISSUE THREAD

**Issue by trevor1097** [Silthus/sLimits#6]
**Describe the bug**
If someone else destroys one of your placed blocks it isn't removed from the limit

**To Reproduce**
1. Place block
2. Someone else mines said block
3. limit is not subtracted

**Expected behavior**
The block should be removed from the players limit if the block is broken

**Screenshots**

**Server Information (please complete the following information):**
- Server version (`/bukkit:version`): git-Paper-273 (1.15.2)
- Installed plugins (`/bukkit:plugins`): 
- WorldGuard Report Pastebin Link (`/wg report -p`):

**Comment by Silthus** [comment]
Yes this is currently the case.
However I am still thinking about the possible implementation here.

- Should it even be possible to destroy limited blocks that are placed by other players? (maybe a config option here?)
- Should it be configurable to not reduce the limit if your block is destroyed by another player? (could be used for some kind of PvP mode)
- What should be the default?

What do you think about those points?

**Comment by trevor1097** [comment]
- I don't think that they should be invincible. In my server and most has some kind of land protection so that would be double work protecting the blocks.
- Not reducing the limit sounds like it could be unfair to a player if something happens to their block.
In the implementation i am using it with Towny. If it just removed the limit when the block is destroyed by another player would be the best.
